rel:
	@cd ive;     make
	@cd dsp;     make
	@cd nnie;     make
clean:
	@cd ive;     make clean
	@cd dsp;     make clean
	@cd nnie;     make clean
cleanall:
	@cd ive;     make clean;   make cleanstream
	@cd dsp;     make clean;   make cleanstream
	@cd nnie;     make clean;   make cleanstream


	
